// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __encode_qq4_code4_table_H__
#define __encode_qq4_code4_table_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct encode_qq4_code4_table_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 16;
  static const unsigned AddressRange = 16;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(encode_qq4_code4_table_ram) {
        ram[0] = "0b0000000000000000";
        ram[1] = "0b1011000000011000";
        ram[2] = "0b1100110110100000";
        ram[3] = "0b1101110011111000";
        ram[4] = "0b1110011101110000";
        ram[5] = "0b1110111101110000";
        ram[6] = "0b1111010111101000";
        ram[7] = "0b1111101101010000";
        ram[8] = "0b0100111111101000";
        ram[9] = "0b0011001001100000";
        ram[10] = "0b0010001100001000";
        ram[11] = "0b0001100010010000";
        ram[12] = "0b0001000010010000";
        ram[13] = "0b0000101000011000";
        ram[14] = "0b0000010010110000";
        ram[15] = "0b0000000000000000";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(encode_qq4_code4_table) {


static const unsigned DataWidth = 16;
static const unsigned AddressRange = 16;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


encode_qq4_code4_table_ram* meminst;


SC_CTOR(encode_qq4_code4_table) {
meminst = new encode_qq4_code4_table_ram("encode_qq4_code4_table_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~encode_qq4_code4_table() {
    delete meminst;
}


};//endmodule
#endif
