// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __encode_quant26bt_pos_H__
#define __encode_quant26bt_pos_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct encode_quant26bt_pos_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 6;
  static const unsigned AddressRange = 31;
  static const unsigned AddressWidth = 5;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(encode_quant26bt_pos_ram) {
        ram[0] = "0b111101";
        ram[1] = "0b111100";
        ram[2] = "0b111011";
        ram[3] = "0b111010";
        ram[4] = "0b111001";
        ram[5] = "0b111000";
        ram[6] = "0b110111";
        ram[7] = "0b110110";
        ram[8] = "0b110101";
        ram[9] = "0b110100";
        ram[10] = "0b110011";
        ram[11] = "0b110010";
        ram[12] = "0b110001";
        ram[13] = "0b110000";
        ram[14] = "0b101111";
        ram[15] = "0b101110";
        ram[16] = "0b101101";
        ram[17] = "0b101100";
        ram[18] = "0b101011";
        ram[19] = "0b101010";
        ram[20] = "0b101001";
        ram[21] = "0b101000";
        ram[22] = "0b100111";
        ram[23] = "0b100110";
        ram[24] = "0b100101";
        ram[25] = "0b100100";
        ram[26] = "0b100011";
        ram[27] = "0b100010";
        ram[28] = "0b100001";
        ram[29] = "0b100000";
        ram[30] = "0b100000";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(encode_quant26bt_pos) {


static const unsigned DataWidth = 6;
static const unsigned AddressRange = 31;
static const unsigned AddressWidth = 5;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


encode_quant26bt_pos_ram* meminst;


SC_CTOR(encode_quant26bt_pos) {
meminst = new encode_quant26bt_pos_ram("encode_quant26bt_pos_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~encode_quant26bt_pos() {
    delete meminst;
}


};//endmodule
#endif
