// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __encode_ilb_table_H__
#define __encode_ilb_table_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct encode_ilb_table_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 12;
  static const unsigned AddressRange = 32;
  static const unsigned AddressWidth = 5;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(encode_ilb_table_ram) {
        ram[0] = "0b100000000000";
        ram[1] = "0b100000101101";
        ram[2] = "0b100001011011";
        ram[3] = "0b100010001010";
        ram[4] = "0b100010111001";
        ram[5] = "0b100011101010";
        ram[6] = "0b100100011100";
        ram[7] = "0b100101001111";
        ram[8] = "0b100110000011";
        ram[9] = "0b100110111001";
        ram[10] = "0b100111101111";
        ram[11] = "0b101000100111";
        ram[12] = "0b101001100000";
        ram[13] = "0b101010011010";
        ram[14] = "0b101011010110";
        ram[15] = "0b101100010010";
        ram[16] = "0b101101010000";
        ram[17] = "0b101110010000";
        ram[18] = "0b101111010001";
        ram[19] = "0b110000010011";
        ram[20] = "0b110001010110";
        ram[21] = "0b110010011100";
        ram[22] = "0b110011100010";
        ram[23] = "0b110100101011";
        ram[24] = "0b110101110100";
        ram[25] = "0b110111000000";
        ram[26] = "0b111000001101";
        ram[27] = "0b111001011100";
        ram[28] = "0b111010101100";
        ram[29] = "0b111011111110";
        ram[30] = "0b111101010010";
        ram[31] = "0b111110101000";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(encode_ilb_table) {


static const unsigned DataWidth = 12;
static const unsigned AddressRange = 32;
static const unsigned AddressWidth = 5;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


encode_ilb_table_ram* meminst;


SC_CTOR(encode_ilb_table) {
meminst = new encode_ilb_table_ram("encode_ilb_table_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~encode_ilb_table() {
    delete meminst;
}


};//endmodule
#endif
