// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __encode_decis_levl_H__
#define __encode_decis_levl_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct encode_decis_levl_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 15;
  static const unsigned AddressRange = 30;
  static const unsigned AddressWidth = 5;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(encode_decis_levl_ram) {
        ram[0] = "0b000000100011000";
        ram[1] = "0b000001001000000";
        ram[2] = "0b000001101110000";
        ram[3] = "0b000010010110000";
        ram[4] = "0b000010111110000";
        ram[5] = "0b000011101001000";
        ram[6] = "0b000100010100000";
        ram[7] = "0b000101000011000";
        ram[8] = "0b000101110010000";
        ram[9] = "0b000110100110000";
        ram[10] = "0b000111011001000";
        ram[11] = "0b001000010010000";
        ram[12] = "0b001001001011000";
        ram[13] = "0b001010001010000";
        ram[14] = "0b001011001010000";
        ram[15] = "0b001100010010000";
        ram[16] = "0b001101011010000";
        ram[17] = "0b001110101100000";
        ram[18] = "0b001111111111000";
        ram[19] = "0b010001100001000";
        ram[20] = "0b010011000011000";
        ram[21] = "0b010100111011000";
        ram[22] = "0b010110110010000";
        ram[23] = "0b011001001100000";
        ram[24] = "0b011011100101000";
        ram[25] = "0b011110111100000";
        ram[26] = "0b100010010011000";
        ram[27] = "0b100111111101000";
        ram[28] = "0b101101100111000";
        ram[29] = "0b111111111111111";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(encode_decis_levl) {


static const unsigned DataWidth = 15;
static const unsigned AddressRange = 30;
static const unsigned AddressWidth = 5;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


encode_decis_levl_ram* meminst;


SC_CTOR(encode_decis_levl) {
meminst = new encode_decis_levl_ram("encode_decis_levl_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~encode_decis_levl() {
    delete meminst;
}


};//endmodule
#endif
